---
 - debug: var=ansible_facts
 
 - name: upgrade all packages
   yum: name=* state=latest
   when: ansible_facts['uptime_seconds']|int <= 100600
   notify:
         - Restart server
         - Wait for server to restart
